INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Biscuit', 434.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Bread roll', 274.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Bread, white', 274.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Buns', 274.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Chapatti (Dry)', 207.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Chapatti with oil', 372.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Donut – African', 316.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Cake', 34.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Cookie', 27.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Donut', 27.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Maize, dried, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Maize, yellow, flour', 11.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Millet, bulrush', 20.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Mixed porridge flour (no maize) 332.2', 332.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Mixed porridge flour (with maize) 382.2', 382.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Rice, fried and boiled 174.0', 87.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Semolina 364.0', 364.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Sorghum 339.0', 339.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Cake (home made)', 208.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize and kidney bean dish', 156.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize and sorgum ugali (stiff porridge)', 110.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize porridge with margarine and sugar', 100.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize porridge no sugar no milk', 36.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize porridge with sugar', 94.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize porridge with sugar and egg', 53.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize porridge with sugar and milk', 55.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Maize ugali (stiff porridge)', 123.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Millet porridge with sugar', 91.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Mix flour porridge with sugar', 130.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Pancake', 38.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice biriyani', 16.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice boiled no Oil', 159.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice boiled with Oil', 199.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice bread  Three recipes', 239.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice bun Two recipes', 416.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice and meat pillau  Three recipes', 177.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice and mung dish with coconut milk Two recipes', 262.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice and mung dish no coconut milk Two recipes', 124.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice poridge with coconut no sugar One recipe', 152.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice porridge with sugar One recipe', 94.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice ugali (stiff porridge)  One recipe', 149.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice with coconut milk Six recipes', 170.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Rice with ground meat One recipe', 288.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Sorgum and millet ugali (stiff porridge)  One recipe', 112.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Sorgum porridge with sugar One recipe', 91.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Vermicelli - cooked  One recipe', 209.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Vermicelli with coconut milk and sugar One recipe', 227.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Vermicell with oil and sugar One recipe', 228.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Vermicelli with coconut milk and salt One recipe', 260.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Wheat fritter, sweet One recipe', 318.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Wheat porridge One recipe', 91.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Breadfruit, raw 103.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Cassava, dried  314.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Cassava, dried, flour 314.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Cassava, raw 160.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Cassava, spicy crisps or chips  288.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Edible starch, tapioca or corn 381.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Potato, raw, with skin 58.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Squash, fresh-AP 16.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Squash, fresh-EP 20.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Taro, raw 112.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B1', 'Yam, raw 97.0', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana porridge, plain', 105.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana porridge with meat', 96.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana porridge with fish', 118.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana porridge with meat and spinach', 212.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana with cashew nut', 108.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana with coconut milk', 191.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana with kidney beans', 93.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana with meat', 77.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana with meat and coconut milk', 130.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana with meat, oil and vegetable', 121.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana with oil  (no meat )', 112.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana,  boiled', 110.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana, fried', 159.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Banana, roast', 116.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Cassava porridge with sugar', 85.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A2', 'Cassava stiff porridge', 140.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Cassava with coconut milk', 216.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Cassava, boiled', 131.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Cassava, fried', 346.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Kachori (spicy potato balls)', 237.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Potato chips, fried', 249.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Potato relish with beef', 128.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Potato relish with coconut milk', 388.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Potato relish with oil', 75.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Potato, boiled', 93.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Roots and tubers mixed', 93.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Sweet potato, boiled', 97.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Sweet potato, fried', 146.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'B2', 'Taro, cooked, without salt', 142.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Almonds', 578.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Bambara groundnut, fresh', 141.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Bean, kidney, green, cooked', 166.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Bean, mung, dry', 116.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Bean, mung, raw', 306.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Beans, kidney, mature, boiled without salt', 127.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Beans, kidney, mature seeds, raw', 333.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Cashewnut', 589.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Chickpea', 164.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Chickpea flour (besan)', 387.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Cowpea, green, uncooked', 116.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Cowpea, uncooked', 336.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Hyancinth beans (dried)', 306.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Hyacinth-beans, immature, raw', 46.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Lentil, cooked', 116.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Lentil, whole', 311.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Palm seed', 16.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Groundnuts', 567.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Peanut butter, smooth', 520.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Pigeon peas, cooked', 121.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Pigeon peas, green', 148.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Pigeon peas, raw', 343.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Pumpkin seed', 435.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Sesame seed', 573.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Soybean, yellow', 415.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Sunflower seed', 588.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Bambara nut relish with coconut milk', 127.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'A1', 'Bhajia (chickpea flour fritters)', 356.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Chick pea relish with coconut milk', 144.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Cow pea (dry) relish without oil', 59.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Cow pea (dry) relish with oil', 154.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Cow pea (fresh) relish without oil', 71.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Cow pea relish with coconut milk', 120.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Kidney bean relish without oil', 117.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Kidney bean relish with oil', 130.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Kidney bean relish with coconut milk', 83.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Mung bean (dry) relish with cocount milk', 87.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Mung bean (dry, boiled)', 43.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Pigeon pea (fresh, cooked)', 131.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Pigeon pea relish with coconut milk', 114.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C2', 'Pigeon pea relish with oil', 245.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Beef liver, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Beef, boneless', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Beef, liver, cooked', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Beef, medium fat, cooked', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Beef, tripe', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Chicken liver', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Chicken, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Egg yolk', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Egg, chicken', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, dried, cod', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, dried, fresh water', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, fresh', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, high fat', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, sardines', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, small, dried, fresh water', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, small, fresh, fresh water', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, smoked, dried-AP', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Fish, smoked, dried-EP', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Goat meat', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Mutton, meat', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Pork, medium fat, cooked', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Sausage', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Beef relish with coconut milk One recipe', 143.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Beef relish without oil One recipe', 168.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Beef  relish with oil Seven recipes', 210.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Beef, fried One recipe', 13.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Beef, ground, relish One recipe', 247.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Chicken, boiled or roasted Two recipes', 285.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Chicken relish without oil Four recipes', 202.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Chicken relish with coconut milk One recipe', 137.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Chicken relish with oil One recipe', 188.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Chicken, fried One recipe', 314.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Egg boiled One recipe', 155.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Egg, fried One recipe', 245.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Fish, fresh, stew  One recipe', 85.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Fish relish without oil Two recipes', 76.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Fish relish with coconut milk Five recipes', 138.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Fish relish with oil Twelve recipes', 253.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Fish, fried One recipe', 230.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Fish, fried, relish Two recipes', 183.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Liver relish One recipe', 14.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Liver, fried  One recipe', 175.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Meat samosaWorldFoods', 280.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Meat, barbecued WorldFoods', 11.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Omelet, spanish  One recipe', 274.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Omelet, spanish with potato Two  recipes', 185.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Small dried fish relish with coconut milk One recipe', 258.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Small dried fish relish with okra One recipe', 98.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Small dried fish with tomatoes and oil Two recipes', 100.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D2', 'Small dried fish, fried One recipe', 449.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Cheese, chedder', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Cheese, cream', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Cheese, mozarella', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Ice cream', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Infant formula, Lactogen', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'D1', 'Milk, condensed, sweetened', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Butter refined-ghee', 61.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Butter with salt', 51.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Coconut cream', 30.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Coconut meat, raw', 29.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Coconut milk and water', 106.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Coconut oil', 86.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Coconut water', 19.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Margarine', 20.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Palm oil', 81.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Sesame oil', 16.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Vegetable fat', 25.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Vegetable fat, Cowboy', 25.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Vegetable fat, Kimbo', 25.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'E', 'Vegetable oil', 86.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Apples, raw, with skin', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Avocado, raw, all common variety', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Banana, ripe', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Baobab, pulp', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Custard-apple (bullock’s heart), raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Date, red, dried', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Date, yellow', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Durian', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Grape', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Grapefruit', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Grapes, pale green', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Guavas, common, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Jackfruit, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Lemon, raw, without peel', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Limes, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Mango juice', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Mango, ripe, fresh-EP', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Mango, unripe', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Orange juice, concentrated, unsweetened', 42.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Orange, raw-AP', 47.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Papaya, ripe', 39.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Papaya, unripe', 39.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Passion, fruit', 43.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Peach', 39.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Pears, raw', 58.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Pineapple juice', 49.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Pineapple, raw, all variety', 48.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Plums, raw', 46.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Raspberry', 52.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Soursop, raw', 66.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Tamarind', 270.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Tamarind, fruit, fresh', 59.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Tangerines, raw', 53.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Watermelon, raw', 30.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F2', 'Apple juice', 53.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F2', 'Avocado juice', 104.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F2', 'Grape juice', 69.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F2', 'Mixed fruit jam', 261.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F2', 'Mixed fruit juice', 45.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F2', 'Papaya juice', 58.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F1', 'Passion juice', 110.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F2', 'Watermelon juice', 111.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Amaranth, leaves, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Bean, cluster', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Bean, french', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cabbage,, chinese, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cabbage, cooked', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cabbage, raw, green, white', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Carrot, juice', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Carrots, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cassava leaf', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cauliflower, cooked without salt', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cauliflower, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Chili, green', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cowpea leaf', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Cucumber, with peel, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Egg plant, raw', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Green medium, leaf', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Green pepper (capsicum)', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Hare lettuce, (mchunga)', 10.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Lettuce', 13.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Mushroom', 27.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Okra, raw', 31.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Onion, raw', 40.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Pea, green, fresh', 84.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Pepper dried or fresh, hot', 27.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Pumpkin leaf, raw', 19.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Pumpkin, cooked', 20.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Salad, green', 36.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Spinach, cooked', 23.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Sweet potato leaf', 35.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Swiss chard, raw', 19.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Taro leaf, raw', 42.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Tomato, bitter (African egg plant)', 22.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Tomato, green', 21.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F3', 'Tomato, ripe', 21.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Cabbage relish with oil', 34.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Cabbage, onion salad', 27.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Cassava leaf relish with groundnuts', 113.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Cassava leaf relish with coconut milk', 70.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Cow pea leaf relish with coconut milk', 80.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Cow pea leaf relish with groundnuts', 79.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Egg plant relish', 77.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green leaf, medium, relish with coconut milk', 107.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green leaf, medium relish with groundnuts', 15.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green leaf, medium, relish without oil', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green leaf, medium, relish with oil', 86.1);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green peas relish without oil', 63.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green peas relish with oil', 82.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green peas relish with oil and coconut milk', 125.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Green peas relish with coconut milk', 120.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Hare lettuce (mchunga)', 169.6);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Okra relish without oil', 16.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Okra relish with oil', 74.3);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Okra relish with coconut milk One recipe', 51.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Okra, fried Two  recipes', 106.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Sweet potato leaf relish with coconut milk One recipe', 11.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Potato leaf relish with milk  One recipe', 67.7);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Potato leaf relish with oil  One recipe', 131.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Potato samosa  worldfoods', 194.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Pumpkin leaf relish without oil One recipe', 16.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Pumpkin leaf relish with oil One recipe', 63.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Spinach relish with groundnut and oil One recipe', 12.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Spinach relish without oil One recipe', 43.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Spinach relish with oil Seven  recipes', 108.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Spinach relish with sesame seeds One recipe', 61.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'F4', 'Tomato relish South African food tables', 34.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Beer, commercial', 41.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Beer, local, grain', 41.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Beer, local, non-specific', 41.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Blackcurrant, syrup, ribena', 338.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Candy, choclate', 17.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Carbonated, beverage, coca cola', 37.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Chili powder, red', 318.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Chili sauce', 169.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'C1', 'Coconut immature, meat and water', 70.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Cod liver oil', 14.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Coffee, instant', 200.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Cricket', 274.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Fruit flavored drink, concentrated', 27.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Garlic, fresh-AP', 149.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Ginger', 66.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Honey', 304.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Ice sherbet', 77.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Orange drink, concentrated', 158.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Soy sauce', 60.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Soybean milk, dried', 380.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Sugar', 387.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Sugarcane', 26.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Sugarcane juice', 56.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Termite', 10.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Tomato juice', 26.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Tomato ketchup', 101.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Tomato paste', 13.8);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'G1', 'Vinegar, wine', 19.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Coffee with milk, without sugar', 11.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Coffee without milk, with sugar,', 35.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Coffee with milk and sugar', 31.5);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Groundnut cluster', 15.2);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Halwa', 10.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Tea with milk, without sugar', 11.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Tea without milk, with sugar', 35.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'Unknown', 'Tea with milk and sugar', 31.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Beef broth without oil', 44.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Beef broth with oil', 88.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cabbage broth without oil', 29.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cabbage broth with oil', 50.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cassava leaf broth without oil', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cassava leaf broth with coconut milk', 21.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cassava leaf broth with oil', 48.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Chicken broth without oil', 91.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Chicken broth with oil', 46.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cow pea broth without oil', 40.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cow pea broth with coconut milk', 102.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cow pea broth with oil', 87.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cow pea leaf broth without oil', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cow pea leaf broth with coconut milk', 15.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Cow pea leaf broth with oil', 42.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Fish broth without oil', 12.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Fish broth with coconut milk', 25.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Fish broth with oil', 55.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Green pea broth without oil', 17.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Green pea broth with coconut milk', 32.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Green Pea Broth with oil', 61.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Ground beef relish broth', 35.4);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Kidney bean broth without oil', 31.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Kidney bean broth with coconut milk', 101.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Kidney bean broth with oil', 48.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Liver relish broth', 12.9);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Pumpkin leaf broth without oil', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Pumpkin leaf broth with oil', 46.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Small dried fish broth with oil', 78.0);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Spinach broth without oil', NULL);
INSERT INTO foods (food_id, food_group, food_name_en, calories_per_100g) VALUES (gen_random_uuid(), 'H', 'Spinach broth with oil', 25.0);
